# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  profiles:
    active:test
---
#dev prfile
spring:
  application:
    name: BootProj09-Profile-Product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springdb
    username: root
    password: 12345
    type: org.apache.commons.dbcp2.BasicDataSource
    
---
#test profile
spring:
  application:
    name: BootProj09-Profile-Product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///springdb
    username: root
    password: 12345
    type: com.mchange.v2.c3p0.ComboPooledDataSource

---
#uat profile
spring:
  application:
    name: BootProj09-Profile-Product
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: ALOKDB
    password: ALOKDB
    type: oracle.ucp.jdbc.PoolDataSourceImpl

---
#prod profile
spring:
  application:
    name: BootProj09-Profile-Product
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: ALOKDB
    password: ALOKDB